(defun brojpoj(el l)
  (cond ((null l) '0)
        ((AND (atom (car l)) (equal el (car l))) (1+ (brojpoj el (cdr l))))
        ((not (atom (car l))) (brojpoj el (car l)))
        (t (brojpoj el (cdr l)))))